// Generated by CoffeeScript 1.12.5

/*$ ->
  xhr = new XMLHttpRequest()

  xhr.onreadystatechange = ->
    if xhr.readyState is 4
      $('#ajax').html xhr.responseText

  xhr.open 'GET', 'jumbotron.html'
  $boton = $('#boton')

  @sendAjax = ->
    xhr.send()
    $boton.hide()
 */


/*
$ ->
  $boton = $('#boton')

  @sendAjax = ->
    $.get 'jumbotron.html', (response) ->
      $('#ajax').html response
      $boton.hide()
 */

(function() {
  $(function() {
    var $boton;
    $boton = $('#boton');
    return this.sendAjax = function() {
      $('#ajax').load('jumbotron.html');
      return $boton.hide();
    };
  });

}).call(this);
